oauth:
  kakao:
    app:
      id: ${KAKAO_APP_ID}
    url:
      validation: https://kapi.kakao.com/v1/user/access_token_info
      user: https://kapi.kakao.com/v2/user/me

naver:
  apiKeyId: ${X-NCP-APIGW-API-KEY-ID}
  apiKey: ${X-NCP-APIGW-API-KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  # 10일
  access-token-time: 864000000
  # 30일
  refresh-token-time: 2592000000

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/docs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    enabled: false
---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:

naver:
  apiKeyId: test-value
  apiKey: test-value

oauth:
  kakao:
    app:
      id: 123456

jwt:
  secret: test-value
---